spring:
  jpa:
    hibernate:
      ddl-auto: update
      dialect: MySQL5InnoDBDialect
    show-sql: true    
  datasource:
    url: jdbc:mysql://localhost:3306/ms_demo?autoReconnect=true
    username: root
    password: 
    dbcp2:
      test-while-idle: true
      validationQuery: SELECT 1
      
  security:
    basic:
      enabled: false

server:
  port: 8082
      


